### PR TITLE
[do not submit] check on all claimed R versions

### PR DESCRIPTION
**Pull request by MichaelChirico**

### CODE REVIEW

**Comment by hadley** [comment]
Out of interest, what's your goal here?

**Comment by MichaelChirico** [comment]
I think if I claim `Depends: R (>=3.4.0)`, ideally the package should work as intended on those versions.

I won't be able to get CI to say anything about 3.4.0/3.5.0 because {testthat} won't install there, but everything else can give useful data.

**Comment by MichaelChirico** [comment]
OK, as of now all of the failures are either (1) #111 or (2) due to R itself being too old. There's also one failure for `{os: macos-13, r: '4.3.2'}`, [looks spurious/flaky](https://github.com/r-lib/bit64/actions/runs/11467497877/job/31910533565).

**Comment by hadley** [comment]
Hmmm, interesting. Our position is that if you're using (e.g.) 4.2.x, you should be using the latest patch version.

FWIW testthat is likely to bump its requirement to 4.0.0 in the next release, so you might want to match that. (i.e. follow https://www.tidyverse.org/blog/2019/04/r-version-support/)

**Comment by MichaelChirico** [comment]
OK, passing on all testable versions now.

**Pull request closed without merging**
